@startuml
title Bond Options: Contract Interactions in the protocol

/' //////////////////////////////////////////////////////////////////
//                      System Participants                        //
////////////////////////////////////////////////////////////////// '/

participant "Roles Authority" as RolesAuthority
actor "Bond Labs (Admin)" as Admin
participant "OTLM Factory" as OTLMFactory
actor "External Team (Issuer)" as Issuer
participant "Manual Strike OTLM" as ManualStrikeOTLM

actor "Alice (User)" as Alice
actor "Bob (User)" as Bob 

participant "Fixed Strike Option Teller" as FixedStrikeOptionTeller
participant "Fixed Strike Option Token (IMPL)" as FixedStrikeOptionToken

participant "Option Token (Instance)" as OptionToken

participant "Token Allow List" as TokenAllowList

participant "Oracle Strike OTLM" as OracleStrikeOTLM


/' //////////////////////////////////////////////////////////////////
//                         Interactions                            //
////////////////////////////////////////////////////////////////// '/
'Numbers are in the A.B.C format, by calling `inc A` you will increase the first number by 1'
autonumber 1.1
group Bond Options - Core Protocol Deployment
    Admin -> RolesAuthority ** : Deploy new Roles Authority contract

    autonumber inc A
    create FixedStrikeOptionTeller
    Admin -> FixedStrikeOptionTeller ++ : Deploy new FixedStrikeOptionTeller
    FixedStrikeOptionTeller -> RolesAuthority : Set //guardian// and //authority//
    create FixedStrikeOptionToken
    FixedStrikeOptionTeller -> FixedStrikeOptionToken : Deploy Option Token implementation for clones
    deactivate

    autonumber inc A
    Admin -> RolesAuthority : Call //setRoleCapability()//\nto allow //role0// call //teller.setProtocolFee()//

    autonumber inc A
    Admin -> RolesAuthority : Call //setRoleCapability()//\nto allow //role0// call //teller.claimFees()//

    autonumber inc A 
    Admin -> RolesAuthority : Call //setUserRole()//\nto assign //guardian// to //role0//
    note left: //guardian// is Bond Labs Multi Sig wallet **???**

    autonumber inc A
    Admin -> OTLMFactory ** : Deploy OTLMFactory
end

autonumber inc A
group Manual Strike Option Token Liquidity Mining - Setup
    Issuer -> TokenAllowList ** : Deploy new TokenAllowList contract
    
    autonumber inc A
    
    Issuer -> OTLMFactory ++ : Call //deploy()// to deploy OTLM
    note left : Args: stakedToken | payoutToken | style
    OTLMFactory -> ManualStrikeOTLM ** : Deploy new ManualStrikeOTLM
    deactivate

    autonumber inc A
    
    Issuer -> ManualStrikeOTLM ++ : call //initialize()//
    note left
        Args: ERC20 quoteToken |
        uint48 timeUntilEligible |
        uint48 eligibleDuration |
        address receiver | uint48 epochDuration |
        uint256 epochTransitionReward |
        uint256 rewardRate |
        IAllowlist allowlist |
        bytes calldata allowlistParams |
        bytes calldata other
    end note

    ManualStrikeOTLM -> TokenAllowList : If //allowList != address(0)//\ntry calling //register()//
    note left : Args: allowlistParams

    ManualStrikeOTLM -> ManualStrikeOTLM: Call //_initialize()// to set initial strike price
    note left : Args: other

    ManualStrikeOTLM -> ManualStrikeOTLM ++ : Call //_startNewEpoch()//\nto start the first epoch

    ManualStrikeOTLM -> ManualStrikeOTLM : Call //nextStrikPrice()// it will be\npassed as strike price to //deploy()//

    ManualStrikeOTLM -> FixedStrikeOptionTeller ++ : //deploy()// new Option Token
    note left
        Args: payoutToken | quoteToken |
        uint48(block.timestamp) + timeUntilEligible |
        uint48(block.timestamp) + timeUntilEligible + eligibleDuration |
        receiver | true | nextStrikePrice()
    end note

    FixedStrikeOptionTeller -> FixedStrikeOptionTeller ++ : //_getPriceDecimals()//
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller -- : External call to //quoteToken.decimals()//
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller: Create option token HASH if one does not exist yet\nInternal Call//_getOptionTokenHash()//
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller ++ : If token[optionHash] does not exist\nCall internal //_deploy()//
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller: Call //_getNameAndSymbol()//
    FixedStrikeOptionTeller -> FixedStrikeOptionToken ++ : Call //clone()// on Impl address\nto deploy new option token
    FixedStrikeOptionToken -> OptionToken **: Create instance (assembly //create()//)
    autonumber stop
    return Option Token
    autonumber resume
    FixedStrikeOptionTeller -> OptionToken --++ : Call //updateDomainSeparator()//
    OptionToken -> OptionToken -- : Update separator with value\nfrom //computeDomainSeparator()//
    autonumber stop
    return OptionToken
    autonumber resume
    deactivate
    deactivate

    == Contract Deployment Finished ==

    autonumber inc A
    Issuer -[#red]> ManualStrikeOTLM : Transfer //1_000_000// Payout TKN 
end

autonumber inc A
group Staking in MOTLM
    Alice -> ManualStrikeOTLM : Approve MOTLM for //1_000// Staked TKN

    autonumber inc A
    Alice -> ManualStrikeOTLM ++ : Call //Stake(1_000)// Staked TKN
    note left : Only users from //AllowList// can stake

    ManualStrikeOTLM -> ManualStrikeOTLM ++ : Modifier //updateRewards()//
    alt lastRewardUpdate != current timestamp 
        ManualStrikeOTLM -> ManualStrikeOTLM -- : Call //currentRewardsPerToken()//\nto set //rewardsPerTokenStored// 
    end
    note right : This also updates //lastRewardUpdate//
    
    ManualStrikeOTLM -> ManualStrikeOTLM ++ : Modifier //tryNewEpoch()//
    alt current timestamp > epochStart + epochDuration
        autonumber stop
        ManualStrikeOTLM --> OptionToken !! : If this was hit, it means that old Option Token is expired
        autonumber resume
        ManualStrikeOTLM -> ManualStrikeOTLM ++ : Call //_startNewEpoch()//
        ManualStrikeOTLM -> FixedStrikeOptionTeller ++ : Call //deploy()// new Option Token
        create OptionToken
        FixedStrikeOptionTeller -> OptionToken -- : Create new instance of Option Token\nProcess exactly the same as in **9.6**
        deactivate

        ManualStrikeOTLM -> FixedStrikeOptionTeller : Approve Option Teller with //epochTransitionReward// of Payout TKN
        ManualStrikeOTLM -> FixedStrikeOptionTeller ++ : Call //create(_optionToken, _amount)//\nIn this case //_amount// is //epochTrReward//
        FixedStrikeOptionTeller -> OptionToken ++ : Call //getOptionParameters(_optionToken)//\nto get basic info about Option Token
        autonumber stop
        return optionParameters
        autonumber resume
        FixedStrikeOptionTeller -> FixedStrikeOptionTeller ++ : Call //getOptionToken(optionParameters)//
        FixedStrikeOptionTeller -> FixedStrikeOptionTeller ++ : Call //_getOptionTokenHash(optionParameters)//
        autonumber stop
        return Hash of the optionParameters
        return optionToken (it's the //optionTokens[optionHash]//)
        autonumber resume

        alt Option is Call: //bool call// (option param) //== true//
            ManualStrikeOTLM -[#red]> FixedStrikeOptionTeller : Safe Transfer //_amount// of Payout TKN
        else Option is Put: //call == false//
            ManualStrikeOTLM -[#green]> FixedStrikeOptionTeller : Safe Transfer //_quoteAmount// of Quote TKN
        end

        FixedStrikeOptionTeller -> OptionToken ++ : Call //mint(msg.sender, _amount)//
        OptionToken -[#purple]> ManualStrikeOTLM -- : Internal //_mint// updates Option TKN\nbalance and total supply
        deactivate

        ManualStrikeOTLM -[#purple]> Alice -- : Transfer //epochTransitionReward// of Option TKN
    end
end

/' //////////////////////////////////////////////////////////////////
//                            Legend                               //
////////////////////////////////////////////////////////////////// '/

legend
    == Legend ==
    ' <font color=orange>Orange</font> - 
    <font color=purple>Purple</font> - Option Token flow
    <font color=blue>Green</font> - Quote Token flow
    <font color=red>Red</font> - Payout Token flow
    <font color=green>Blue</font> - Staked Token flow
endlegend

/' //////////////////////////////////////////////////////////////////
//                            Styling                              //
////////////////////////////////////////////////////////////////// '/

skinparam sequenceMessageAlign center

skinparam note {
    BorderColor black
    BackgroundColor white
    FontColor black
}

skinparam participant {
    FontSize 25
    BackgroundColor lightgray
}

footer Bond Options - Sherlock (Jul 2023) - PlantUML diagram | author: @kamilchmielu
@enduml
