@startuml
title Bond Options: Contract Interactions in the protocol

/' //////////////////////////////////////////////////////////////////
//                      System Participants                        //
////////////////////////////////////////////////////////////////// '/

actor "Bond Labs (Admin)" as Admin
participant "OTLM Factory" as OTLMFactory
actor "External Team (Issuer)" as Issuer
participant "Manual Strike OTLM" as ManualStrikeOTLM

participant "Token Allow List" as TokenAllowList

participant "Fixed Strike Option Teller" as FixedStrikeOptionTeller
participant "Fixed Strike Option Token (IMPL)" as FixedStrikeOptionToken

participant "Option Token (Instance)" as OptionToken

actor "Alice (User)" as User

participant "Oracle Strike OTLM" as OracleStrikeOTLM


/' //////////////////////////////////////////////////////////////////
//                         Interactions                            //
////////////////////////////////////////////////////////////////// '/
'Numbers are in the A.B.C format, by calling `inc A` you will increase the first number by 1'
autonumber 1.1
group Bond Options - Core Protocol Deployment
    Admin -> FixedStrikeOptionTeller ** : Deploy new FixedStrikeOptionTeller
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller : Set //guardian// and //authority//
    FixedStrikeOptionTeller -> FixedStrikeOptionToken ** : Deploy Option Token implementation for clones
    |||
    autonumber inc A
    Admin -> OTLMFactory ** : Deploy OTLMFactory
end

autonumber inc A
group Manual Strike Option Token Liquidity Mining - Setup
    Issuer -> OTLMFactory ++ : Call //deploy()// to deploy OTLM
    note left : Args: stakedToken | payoutToken | style
    OTLMFactory -> ManualStrikeOTLM ** : Deploy new ManualStrikeOTLM
    deactivate

    autonumber inc A

    Issuer -> TokenAllowList ** : Deploy new TokenAllowList contract

    autonumber inc A
    
    Issuer -> ManualStrikeOTLM ++ : call //initialize()//
    note left
        Args: ERC20 quoteToken |
        uint48 timeUntilEligible |
        uint48 eligibleDuration |
        address receiver | uint48 epochDuration |
        uint256 epochTransitionReward |
        uint256 rewardRate |
        IAllowlist allowlist |
        bytes calldata allowlistParams |
        bytes calldata other
    end note

    ManualStrikeOTLM -> TokenAllowList : If //allowList != address(0)//\ntry calling //register()//
    note left : Args: allowlistParams

    ManualStrikeOTLM -> ManualStrikeOTLM: Call //_initialize()// to set initial strike price
    note left : Args: other

    ManualStrikeOTLM -> ManualStrikeOTLM ++ : Call //_startNewEpoch()//\nto start the first epoch

    ManualStrikeOTLM -> ManualStrikeOTLM : Call //nextStrikPrice()// it will be\npassed as strike price to //deploy()//

    ManualStrikeOTLM -> FixedStrikeOptionTeller ++ : //deploy()// new Option Token
    note left
        Args: payoutToken | quoteToken |
        uint48(block.timestamp) + timeUntilEligible |
        uint48(block.timestamp) + timeUntilEligible + eligibleDuration |
        receiver | true | nextStrikePrice()
    end note

    FixedStrikeOptionTeller -> FixedStrikeOptionTeller ++ : //_getPriceDecimals()//
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller -- : External call to //quoteToken.decimals()//
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller: Create option token HASH if one does not exist yet\nInternal Call//_getOptionTokenHash()//
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller ++ : If token[optionHash] does not exist\nCall internal //_deploy()//
    FixedStrikeOptionTeller -> FixedStrikeOptionTeller: Call //_getNameAndSymbol()//
    FixedStrikeOptionTeller -> FixedStrikeOptionToken ++ : Call //clone()// on Impl address\nto deploy new option token
    FixedStrikeOptionToken -> OptionToken **: Create instance (assembly //create()//)
    autonumber stop
    return Option Token
    autonumber resume
    FixedStrikeOptionTeller -> OptionToken --++ : Call //updateDomainSeparator()//
    OptionToken -> OptionToken -- : Update separator with value\nfrom //computeDomainSeparator()//
    autonumber stop
    return OptionToken
    autonumber resume
    deactivate
    deactivate
end

/' //////////////////////////////////////////////////////////////////
//                            Legend                               //
////////////////////////////////////////////////////////////////// '/

legend
    == Legend ==
    <font color=orange>Orange</font> - 
    <font color=purple>Purple</font> - 
    <font color=blue>Blue</font> - 
    <font color=red>Red</font> - 
    <font color=green>Green</font> - 
endlegend

/' //////////////////////////////////////////////////////////////////
//                            Styling                              //
////////////////////////////////////////////////////////////////// '/

skinparam sequenceMessageAlign center
skinparam note {
    BorderColor black
    BackgroundColor white
    FontColor black
}
skinparam participant {
    FontSize 25
    BackgroundColor lightgray
}

footer Bond Options - Sherlock (Jul 2023) - PlantUML diagram | author: @kamilchmielu
@enduml
